### ISSUE TITLE
Benchmark to become GDE and Github star

### ISSUE THREAD

**Issue by patelvimal** [santoshyadavdev/ama#1]
Following questions are all related to Angular Framework for both GDE and Github Star.

- Is there any benchemark to become GDE and GIthub Star?  
- Is it required to contribute to angular github source code?
- How does they evaluate your knowledge?

**Comment by santoshyadavdev** [comment]
Hey @patelvimal ,

* Is there any benchemark to become GDE and GIthub Star?
	- Both programs looks for someone who has a passion to teach, GitHub Star looks for someone who is also doing Open Source
	- If you want to be one, focus on
		- Teaching and Helping Community: GitHub Discussion, Stackoverflow are the best areas to help
		- Create Content: write blogs, do a live stream, create video contents
		- Give Talks: Start speaking in meetups, conferences ot podcasts
		- Start Contributing to Open Source: Get involved with any Open Source Project, help them with documents, feature, bugs 		 	
* Is it required to contribute to angular github source code?
	- No not required
* How does they evaluate your knowledge?
	- For GDE you will be evaluated based on your community contribution and you will be interviewed by one of the GDE if your application is accepted
	- For GitHub star it's based on your contribution, there is no interview.

Hope it helps

**Comment by patelvimal** [comment]
Thanks @santoshyadavdev for answering those questions.
So in a nutshell, lets focus on community works and dont think about these things at all which is the correct way to go as well.

**Comment by santoshyadavdev** [comment]
💯 just focus on sharing your knowledge, titles will come to you
