### ISSUE TITLE
How to become a pro developer

### ISSUE THREAD

**Issue by Amankumar05** [santoshyadavdev/ama#2]
As i am student in IIIT in 1st year and i don't know about web development and i am not pro in C++ aur Java how to start and become a pro and become a competitive coder and developer

**Comment by santoshyadavdev** [comment]
Hey @Amankumar05,

Thats great that you want to start early, it is ok you don't know anything as of now, everyone starts at the same stage.

First, decide what you want to focus on is it Web Development, which has a different path, or you want to move into DSA and CP.

There are tons of options for both.
* For web development,
- Start with HTML and CSS 
- Move to JavaScript and Gradually move to Typescript.
- Once you know the basics of Typescript/JavaScript start building something Freecodecamp has tons of resources.
- Start sharing whatever you build with everyone on Twitter and keep your code on GitHub 
- Ask for help if you are stuck
- Participate in Hackathons

* For DSA or CP
- There are many websites like leetcode 
- Tons of YouTube channel 
- Tons of udemy courses
- Also Google Has https://codingcompetitions.withgoogle.com/codejam CodeJam where you can participate and learn

Hope it helps
