### ISSUE TITLE
How can i become a pro backend developer

### ISSUE THREAD

**Issue by Henrymenez** [santoshyadavdev/ama#3]
I've been learning nodes for about four months now, but I need to go pro now and start building real money making products. How can i move up from junior to pro backend Dev

**Comment by santoshyadavdev** [comment]
HI @Henrymenez,

Start small, if you have any product-making ideas start working on it, everything takes time.

Here is a blog on How you can build a SaaS Product:
https://www.codica.com/blog/how-to-build-saas-product/

You can also check out https://www.asyncapi.com/ for building APIs.

And remember becoming a Pro is all about coming across issues, having patience, and a lot of practice and it doesn't happen in a month, takes time.
